### ISSUE TITLE
fix:  Upgrade to web ^1.0.0

### ISSUE THREAD

**Issue by ZoftPranav** [felangel/web_socket_client#62] opened 2024-09-23 13:30 UTC
**Description**

Please upgrade web to web ^1.0.0 as many other packages are unable to be updated.

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by ZoftPranav** [comment] 2024-09-24 07:17
can somebody provide a fix for this

**Comment by felangel** [comment] 2024-09-24 14:42
> can somebody provide a fix for this @felangel

Sure I should be able to have a look later this evening 👍

**Comment by ZoftPranav** [comment] 2024-09-25 03:25
@felangel  Here is the error :

Because no versions of web_socket_client match >0.1.4 <0.2.0 and web_socket_client 0.1.4 depends on web ^0.5.0, web_socket_client ^0.1.4 requires web ^0.5.0.
And because flutter_inappwebview >=6.1.0 depends on flutter_inappwebview_web ^1.1.0 which depends on web ^1.0.0, web_socket_client ^0.1.4 is incompatible with
  flutter_inappwebview >=6.1.0

**Comment by felangel** [comment] 2024-09-25 04:45
> @felangel Here is the error :
> 
> Because no versions of web_socket_client match >0.1.4 <0.2.0 and web_socket_client 0.1.4 depends on web ^0.5.0, web_socket_client ^0.1.4 requires web ^0.5.0. And because flutter_inappwebview >=6.1.0 depends on flutter_inappwebview_web ^1.1.0 which depends on web ^1.0.0, web_socket_client ^0.1.4 is incompatible with flutter_inappwebview >=6.1.0

Can you share your `pubspec.yaml` and the output of `flutter doctor --verbose`? Thanks!

**Comment by felangel** [comment] 2024-09-25 04:48
Ah nevermind, the issue is I never published the latest version. Doing that now, apologies for the inconvenience!

**Comment by ZoftPranav** [comment] 2024-09-25 04:50
@felangel  Thank you

**Comment by felangel** [comment] 2024-09-25 04:52
Just published v0.1.5 which should resolve this. 🎉
Closing for now but let me know if you run into any issues using 0.1.5.

**Closed by felangel** 2024-09-25 04:52 UTC
Labels: question
