### ISSUE TITLE
Does not handle errors emitted by web socket channel or thrown inside listen

### ISSUE THREAD

**Issue by saibotma** [felangel/web_socket_client#56] opened 2024-06-21 09:50 UTC
I did not test this or experience a bug, but after looking at the source code, I noticed that an error emitted by the web socket channel or thrown inside listen never gets handled.

```dart
Future<void> _connect() async {
  // ..

  void attemptToReconnect([Object? error, StackTrace? stackTrace]) {
    // ..
  }

  try {
    // ..
    _channel!.stream.listen(
          (message) {
        if (_messageController.isClosed) return;
        _messageController.add(message);
      },
      onDone: attemptToReconnect,
      cancelOnError: true,
    );
  } catch (error, stackTrace) {
    attemptToReconnect(error, stackTrace);
  }
}

```

Due to `onDone` not getting called, when the stream gets cancelled because of an error, `attemptToReconnect` will never be called in this case. In addition to that, an error thrown inside `listen` will put the web socket client in a kind of zombie state, because the error isn't propagated up and never handled inside `listen`.

So from my point of view the solutions would be:
- Add `onError` and call `attemptToReconnect` in it. 
- Wrap the body of `listen` in a try catch and call `attemptToReconnect` inside catch.

I could be wrong, but wanted to point this out.

**Comment by felangel** [comment] 2024-06-21 14:04
Thanks for filing an issue! I don’t think that’s necessary as the message stream should never contain errors. If you feel this is still an issue it’d be most helpful if you could create a simple reproduction sample which illustrates the issue and I’m happy to take a closer look, thanks!

**Comment by felangel** [comment] 2024-06-21 14:07
Thanks for filing an issue! I don’t think this is an issue since cancelOnError is true and we should catch the error and attempt to reconnect as is. Happy to look at a simple reproduction sample if you have one that illustrates incorrect behavior though, thanks!

**Comment by felangel** [comment] 2024-06-27 23:31
Closing for now since there are no actionable next steps without a reproduction sample.

**Closed by felangel** 2024-06-27 23:31 UTC
Labels: question
