### ISSUE TITLE
Expose a method to update connection uri in case of passing token parameter

### ISSUE THREAD

**Issue by Danny-Hoang** [felangel/web_socket_client#37] opened 2024-01-26 10:52 UTC
URI is init each time Websocket instance is create, and reuse it for every reconnect attempt. That is sometime a problem.
If I pass a jwt token to the uri then if the token is expired I always have to call the method close and create new WebSocket instance, update the uri with new token.
It is convenient if the uri value can be expose and modify outside.

**Comment by felangel** [comment] 2024-06-08 21:37
Hi @Danny-Hoang 👋 
Thanks for opening an issue! This seems to be a duplicate of #31 so closing in favor of the other issue 👍

**Closed by felangel** 2024-06-08 21:37 UTC
Labels: enhancement
